{% set name = "opentelemetry-instrumentation-pymongo" %}
{% set version = "0.53b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pymongo-{{ version }}.tar.gz
  sha256: 525088063ff790c12b89c6a97617841d43e51975604d957ca818122fb47760bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.53b1
    - opentelemetry-semantic-conventions ==0.53b1
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymongo
  summary: OpenTelemetry pymongo instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
