{% set name = "opentelemetry-instrumentation-pymongo" %}
{% set version = "0.49b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pymongo-{{ version }}.tar.gz
  sha256: 44b964baa009c925837b72d0462258d05a04f00cf7a9f66ebfdcf9517449f004

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.49b1
    - opentelemetry-semantic-conventions ==0.49b1
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
    # - pymongo <5.0,>=3.1
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymongo
  summary: OpenTelemetry pymongo instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
